# SPEEDS
VERY_SLOW = 20
SLOW = 90
MODERATE = 200
FAST = 360
FASTER = 650
VERY_FAST = 720
ULTRA_FAST = 1250

# SENSOR PORTS
COLOR_SENSOR = 1
COLOR_SENSOR_STICKER = 4
US_PORT = 2
US_PORT_2 = 3
INITILIALIZATION_TIME = 1

# MOTORS PORTS
LEFT_WHEEL_PORT = "C"
RIGHT_WHEEL_PORT = "B"
ARM_PORT = "A"
DUMB_PORT = "D"

#some constants
WHEEL_TO_CAR_DEGREE_RATIO = 1.9722
SLEEP_TIME = 0.2
LOOP_INTERVAL = 0.05
EMERGENCY_STOP_DISTANCE = 10
CHECK_WALL_DISTANCE = 13
WALL_CHECK_TIME = 2

#ARM CONSTANTS
PICK_UP_ANGLE = 320
INIT_ANGLE = 0
CHECK_COLOR_ANGLE = 105
POOP_CHECK_TIME = 1
PICKUP_DISTANCE_LOWER = 3
PICKUP_DISTANCE_UPPER = 4
INIT_GRIPPER_TIME = 1
CHECK_WALL_ANGLE = 220
